accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name="accounts"

urlpatterns = [
    #サインアップビューの呼び出し
    path("signup/",views.SignUpView.as_view(),name="signup"),

    #サインアップ完了
    path("signup-success/",views.SignUpSuccessView.as_view(),name="signup_success"),

    #ログインページの表示
    path("login/",auth_views.LoginView.as_view(template_name="login.html"),name="login"),

    #ログアウトページ
    path("logout/",auth_views.LogoutView.as_view(template_name="logout.html"),name="logout"),
    
]

photo/urls.py
from django.urls import path
from . import views

app_name="photo"

urlpatterns = [
    path("",views.IndexView.as_view(),name="index"),

    #写真投稿ページ
    path("post/",views.CreatePhotoView.as_view(),name="post"),

    #投稿完了ページ
    path("post-done/",views.PhotoSuccessView.as_view(),name="post_done"),

    #カテゴリ一覧ページ
    path("photos/<int:category>",views.CategoryView.as_view(),name="photos_cat"),

    #ユーザーの投稿一覧ページ
    path("user-list/<int:user>",views.UserView.as_view(),name="user_list"),

    #詳細ページ
    #<int:pk>は辞書{pk:id値}としてDetailViewに渡される
    path("photo-detail/<int:pk>",views.DetailView.as_view(),name="photo_detail"),

    #マイページ
    path("mypage/",views.MypageView.as_view(),name="mypage"),

    #投稿写真の削除
    path("photo/<int:pk>/delete/",views.PhotoDeleteView.as_view(),name="photo_delete")
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #photo.urlsへのURLパターン
    path("",include("photo.urls")),

    #accounts.urlへのURLパターン
    path("",include("accounts.urls")),

    #パスワードリセットのためのURLパターン
    #PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載

    #パスワードリセット申し込みページ
    path("password-reset/",auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name="password_reset"),

    #メール送信完了ページ
    path("password-reset/done/",auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name="password_reset_done"),

    #パスワードリセットページ
    path("reset/<uidb64>/<token>",auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),name="password_reset_confirm"),

    #パスワードリセット完了ページ
    path("reset/done/",auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),name="password_reset_complete")
]


#urlpatternsにmediaフォルダーのURLパターンを追加
urlpatterns+=static(
    #MEDIA_URL="media/"
    settings.MEDIA_URL,
    #MEDIA_URLにリダイレクト
    document_root=settings.MEDIA_ROOT
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    #Userモデルを継承したカスタムユーザー
    pass

photo/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.

class Category(models.Model):
    #投稿する写真のカテゴリを管理するモデル

    #カテゴリ名のフィールド
    title=models.CharField(
        verbose_name="カテゴリ",
        max_length=20,
    )

    def __str__(self):
        return self.title


class PhotoPost(models.Model):
    #投稿されたデータを管理するモデル

    #CustomUserモデルのuser_idとPhotoPostモデルを1対多の関係で結びつける
    #CustomUserが親でPhotoPostが子
    user=models.ForeignKey(
        CustomUser,
        verbose_name="ユーザー",
        #ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
    )

    #CategoryモデルのtitleとPhotoPostモデルを1対多の関係で結びつける
    #Categoryが親でPhotoPostが子
    category=models.ForeignKey(
        Category,
        verbose_name="カテゴリ",
        #カテゴリに関連づけられた投稿データが存在する場合はそのカテゴリを削除できないようにする
        on_delete=models.PROTECT
    )

    #タイトル用のフィールド
    title=models.CharField(
        verbose_name="タイトル",
        max_length=200
    )

    #コメント用のフィールド
    comment=models.TextField(
        verbose_name="コメント"
    )

    #イメージのフィールド1
    image1=models.ImageField(
        verbose_name="イメージ1",
        upload_to="photos" #MEDIA_ROOT以下のphotosにファイルを保存
    )

    #イメージのフィールド2
    image2=models.ImageField(
        verbose_name="イメージ2",
        upload_to="photos",
        blank=True, #フィールドの値の設定は必須ではない
        null=True  #データベースにnullが保存されることを許容
    )

    #投稿日時のフィールド
    posted_at=models.DateTimeField(
        verbose_name="投稿日時",
        auto_now_add=True
    )
    
    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    #UserCreationFormのサブクラス

    class Meta:
        #連携するUserモデルを設定
        model=CustomUser
        #フォームで使用するフィールドを設定
        fields=("username","email","password1","password2")

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    #ModelFormのサブクラス

    class Meta:
        #ModelFormのインナークラス
        model=PhotoPost #モデルのクラス
        fields=["category","title","comment","image1","image2"] #フォームで使用するモデルのフィールド

accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

# Create your views here.

class SignUpView(CreateView):
    #サインアップのビュー

    form_class=CustomUserCreationForm

    template_name="signup.html"
    success_url=reverse_lazy("accounts:signup_success")

    def form_invalid(self, form):

        user=form.save()
        self.object=user

        return super().form_invalid(form)


class SignUpSuccessView(TemplateView):
    #サインアップ成功ビュー
    template_name="signup_success.html"

photo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView,ListView,DetailView,DeleteView
from django.urls import reverse_lazy
from .forms import PhotoPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import PhotoPost

# Create your views here.

class IndexView(ListView):
    template_name="index.html"

    #投稿日時の降順で並び変える
    queryset=PhotoPost.objects.order_by("-posted_at")

    #1ページに表示するレコードの件数
    paginate_by=9

#デコレーターにより、ログイン中にのみこのビューを実行できる
@method_decorator(login_required,name="dispatch")
class CreatePhotoView(CreateView):
    #写真投稿ページのビュー
    
    #PhotoPostで定義されているモデルとフィールドを連携して投稿データをデータベースに登録する

    #forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class=PhotoPostForm
    #レンダリングするテンプレート
    template_name="post_photo.html"
    #フォームデータ登録完了後のリダイレクト先
    success_url=reverse_lazy("photo:post_done")

    def form_valid(self, form):
        #フォームが送信された際に呼び出される関数

        #POSTデータを取得
        postdata=form.save(commit=False)
        #投稿データのidを取得してモデルのuserフィールドに格納
        postdata.user=self.request.user
        #投稿データをデータベースに登録
        postdata.save()

        return super().form_valid(form)


class PhotoSuccessView(TemplateView):
    #投稿完了ページのビュー

    #レンダリングするファイル
    template_name="post_success.html"


class CategoryView(ListView):
    #カテゴリページのビュー

    #index.htmlをレンダリングする
    template_name="index.html"
    #1ページに表示するレコードの件数
    paginate_by=9

    def get_queryset(self):
        #クエリを実行する

        #self.kwargsの取得が必要なためクラス変数querysetではなく、get_queryset()のオーバーライドにてクエリを実行する
        
        #カテゴリのidを取得する
        category_id=self.kwargs["category"]
        #filter(フィールド名=id)絞り込む
        categories=PhotoPost.objects.filter(category=category_id).order_by("-posted_at")
        
        #クエリによって取得されたレコードを返す
        return categories


class UserView(ListView):
    #ユーザーの投稿一覧ページのビュー

    #index.htmlをレンダリングする
    template_name="index.html"
    #１ページに表示するレコードの件数
    paginate_by=9

    def get_queryset(self):
        #クエリを実行する

        #userキーの値を取得
        user_id=self.kwargs["user"]
        #fillterで絞り込む
        user_list=PhotoPost.objects.filter(user=user_id).order_by("-posted_at")

        #レコードを返す
        return user_list

class DetailView(DetailView):
    #詳細ページのビュー

    #投稿記事の詳細を表示するのでDetailViewを継承する

    #detail.htmlをレンダリングする
    template_name="detail.html"
    #クラス変数modelにモデルPhotoPostを定義
    model=PhotoPost


class MypageView(ListView):
    #マイページのビュー

    #mypage.htmlをレンダリングする
    template_name="mypage.html"
    #1ページに表示するレコードの件数
    paginate_by=9

    def get_queryset(self):
        #クエリの実行

        #現在ログインしているユーザー名はHttpResoponce.userに格納されている
        queryset=PhotoPost.objects.filter(user=self.request.user).order_by("-posted_at")

        return queryset


class PhotoDeleteView(DeleteView):
    #レコードの削除を行うビュー

    #操作の対象はPhotoPostモデル
    model=PhotoPost
    #photo_delete.htmlをレンダリング
    template_name="photo_delete.html"
    #処理完了後のマイページにリダイレクト
    success_url=reverse_lazy("photo:mypage")

    def delete(self,request,*args,**kwargs):
        #レコードの削除を行う

        #スーパークラスのdelete()を実行
        return super().delete(request,*args,**kwargs)

accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Log in</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static "css/signin.css" %}" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
  <!--ユーザー名とパスワードが一致しない場合-->
  {% if form.errors %}
    <p style="color: red;">ユーザー名とパスワードが一致しません</p>
  {% endif %}
  <!--ログインフォームを配置-->
  <form method="post">
    {% csrf_token %}
    <img src="{% static "img/bootstrap-logo.svg" %}" alt="bootstrap" class="mb-4" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <!--Usernameのラベル-->
    <label for="Username" class="visually-hidden">User name</label>
    <!--inputタグの出力-->
    <input type="text" name="username" id="id_username" maxlength="150" autocapitalize="none" autocomplete="username" class="form-control" placeholder="ユーザー名" required autofocus>

    <!--Passwordのラベル-->
    <label for="Password" class="visually-hidden">Password</label>
    <!--inputタグの出力-->
    <input type="password" name="password" id="id_password" autocomplete="current-password" class="form-control" placeholder="パスワード" required autofocus>

    <!--ログインボタン-->
    <input type="submit" value="ログイン" class="w-100 btn btn-lg btn-primary">

    <br><br>
    <p><a href="{% url "password_reset" %}">パスワードを忘れましたか?</a></p>
    <!--ログイン直後のリダイレクト先-->
    <input type="hidden" name="next" value="{% url "photo:index" %}">
  </form>
</main>


    
  </body>
</html>

accounts/templates/logout.html
<!--ベーステンプレートを適用-->
{% extends 'base.html' %}

{% block title %}
    Log out
{% endblock title %}
    

{% block contents %}
<br><br><br><br>
    <div class="container">
        <siv class="row">
            <div class="col offset-4 py-4">
                <h3>ログアウトしました</h3>

                <p><a href="{% url "photo:index" %}">トップページ</a></p>
            </div>
        </siv>
    </div>
{% endblock contents %}
    

accounts/templates/password_reset.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock  %}

{% block contents %}
<br><br>
    <div class="container">
        <div class="row">
            <div class="col py-4">
                <hr>
                <h3>パスワードをリセットしますか</h3>
                <p>登録済みのメールアドレスを入力してください。
                    パスワードリセットのリンクを記載したメールをすぐにお届けします。
                </p>
                <br>
                <!--メール送信のためのフォーム-->
                <form action="" method="post" class="text-center">
                    {% csrf_token %}
                    <!--formに格納されているインプットボックスとラベルを出力-->
                    {{form}}
                    <!--送信ボタン-->
                    <input type="submit" value="メールを受け取る" /><br>
                </form>
                <br>
                <!--トップページへのリンク-->
                <a href="{% url "photo:index" %}">Yoshimo Gallery</a>
                <hr>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/password_reset_done.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <style>
        .pad{
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
        }
    </style>
</head>
<body>
    <div class="pad">
        <h2>パスワードがリセットされました。</h2>
        <p>Your Password has been set.You may go ahead and login</p>
        <br>
        <!--トップページへのリンク-->
        <a href="{% url "photo:index" %}">Photo Galleryのトップページへ</a>
    </div>
</body>
</html>

accounts/templates/password_reset_form.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <style>
        .pad{
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
        }
    </style>
</head>
<body>
    <div class="pad">
        <h2>Photo Gallery</h2>
        <h4>
            新しいパスワードを2回入力してください。これにより、
            正しく入力できたことが確認されます。
        </h4>
        <br>
        <!---フォームを配置-->
        <form action="" method="post">
            {% csrf_token %}
            <!--formに格納されている要素を全て出力-->
            {{form}}
            <input type="submit" value="パスワードリセット">
        </form>
    </div>
</body>
</html>

accounts/templates/password_reset_sent.html
<!--ベーステンプレートを適用-->
{% extends "base.html" %}

<!--ヘッダー情報のページタイトルを設定する-->
{% block title %}Send password reset{% endblock %}

{% block contents %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2 py-4">
                <h5>パスワードのリセット手順をメールで送信しました。メールはすぐに届きます。</h5>
                <br>
                <h6>
                    メールが届かない場合は、登録済みのメールアドレスであるかを確認し、
                    迷惑メールフォルダーも確認してみてください。
                </h6>
                <br>
                <!--トップページへのリンク-->
                <a href="{% url "photo:index" %}">Photo Gallery</a>
            </div>
        </div>
    </div>
{% endblock  %}

accounts/templates/signup.html
<!--ベーステンプレートを適用-->
{% extends 'base.html' %}

{% block title %}
    Sign up
{% endblock title %}

{% block contents %}
    <br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h3>サインアップ</h3>
                <form method="post">
                    {% csrf_token %}
                    
                    {% for field in form %}
                        <p>
                            {{field.label_tag}}
                            {{field}}
                            
                            {% if field.help_text %}
                                <small style="color: gray;">{{field.help_text}}</small>
                            {% endif %}
                            
                            {% for error in fields.error %}
                                <p style="color: red;">{{error}}</p>
                            {% endfor %}
                        </p>
                    {% endfor %}
                    <p style="color: red;">
                        *メールアドレスはパスワードをリセットする際に必要になりますので、
                        登録をお願いします。
                    </p>
                    <input type="submit" value="Sign up">
                </form>
                <br>
                <p><a href="{% url "photo:index" %}">登録をやめてトップページに戻る</a></p>
            </div>
        </div>
    </div>
{% endblock contents %}

accounts/templates/signup_success.html
<!--ベーステンプレートを適用-->
{% extends 'base.html' %}

{% block title %}
    Registration Complete
{% endblock title %}


{% block contents %}
<br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
                <h3>登録が完了しました</h3>
                <!--ログイン誘導-->
                <p><a href="{% url "accounts:login" %}">ログインはこちら</a></p>
            </div>
        </div>
    </div>
{% endblock contents %}
    

photo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link rel="icon" type="image/x-icon" href="{% static "img/bigyoshimo.ico" %}">
    <title>{% block title %}{% endblock  %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      header{
        position: fixed;
        width: 100%;
        z-index: 10;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">お気に入りを見つけよう!</h4>
          <p class="text-muted">
            誰でも参加できる写真投稿サイトです。自分で撮影した写真なら何でもオッケー!
            でも、カテゴリに属する写真に限ります。コメントも付けてください!
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <!--ナビゲーションメニュー-->
            
            {% if user.is_authenticated %}
            <!--ログイン中の場合-->
              <li><a href="{% url "photo:mypage" %}" class="text-white">マイページ</a></li>
              <li><a href="{% url "accounts:logout" %}" class="text-white">ログアウト</a></li>
            <!--ログインしていない場合-->
            {% else %}
              <li><a href="{% url "accounts:signup" %}" class="text-white">サインアップ</a></li>
              <li><a href="{% url "accounts:login" %}" class="text-white">ログイン</a></li>
            {% endif %}
              
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url "photo:index" %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Yoshimo Gallery</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
  {% block contents %}{% endblock  %}
</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="{% url "photo:index" %}">Back to top</a>
    </p>
  </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

      
  </body>
</html>

photo/templates/detail.html
<!--ベーステンプレートを適用-->
{% extends 'base.html' %}



{% block contents %}
    <br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-1">
                <!--タイトル-->
                <h2>{{object.title}}</h2>
                <!--コメント-->
                <p>{{object.comment}}</p>
                <br>
                <!--投稿日時-->
                <p>{{object.posted_at}}に投稿</p>
                <!--1枚目の写真-->
                <p><img src="{{object.image1.url}}" alt="写真"></p>
                <!--2枚目の写真がとうこうされていたら表示する-->
                
                {% if object.image2 %}
                    <p><img src="{{object.image2.url}}" alt="写真2"></p>
                {% endif %}
                <!--投稿写真がログイン中のユーザーのものであれば削除ボタンを配置-->
                {% if request.user == object.user %}
                    <form method="post">
                        <a href="{% url "photo:photo_delete" object.pk %}" class="btn btn-primary my-2">削除する</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock contents %}
    

photo/templates/index.html
<!--ベーステンプレートを適用-->
{% extends 'base.html' %}

{% block title %}
  Yoshimo Gallery
{% endblock title %}

{% block contents %}
  <!--タイトルテンプレートの読み込み-->
  {% include 'photos_title.html' %}

  <!--投稿一覧テンプレートの読み込み-->
  {% include 'photos_list.html' %}
  <!--ページネーションの読み込み-->
  {% include 'pagination.html' %}
{% endblock contents %}

photo/templates/mypage.html
<!--ベーステンプレートを適用-->
{% extends 'base.html' %}


{% block title %}
    Mypage
{% endblock title %}


{% block contents %}
    <br><br>
    <!--ユーザーの投稿件数を表示-->
    {% if user.is_authenticated %}
        <br>
        <div style="text-align: center;">
            <h4>{{user.username}}さんのマイページ</h4>
            
            {% if object_list.count == 0 %}
                <p>{{user.username}}さんの投稿はありません</p>
            {% else %}
                <p>投稿<strong>{{object_list.count}}</strong>件</p>
            {% endif %}
        </div>

            <!--投稿一覧テンプレート-->
            {% include 'photos_list.html' %}

            <!--ページネーション-->
            {% include 'pagination.html' %}
        
    {% endif %}
{% endblock contents %}
    
    

photo/templates/photo_delete.html
<!--ベーステンプレートを適用-->
{% extends 'base.html' %}

{% block title %}
    photo Detail
{% endblock title %}


{% block contents %}
    <br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="post">
                    <br>
                    <p>削除してもいいですか?</p>
                    {% csrf_token %}
                    <button class="btn btn-primary my-2" type="submit">削除</button>
                    <a class="btn btn-secondary my-2" href="{% url "photo:photo_detail" object.pk %}">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
{% endblock contents %}
    
    

photo/templates/photos_list.html
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for record in object_list %}
      <div class="col">
        <div class="card shadow-sm">
          <!--画像の表示-->
          <img class="bd-placeholder-img card-img-top" src="{{record.image1.url}}" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>
          <div class="card-body">
            <!--タイトル-->
            <p class="card-text">
              {{record.title}}
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <!--ボタングループ-->
              <div class="btn-group">
                <!--詳細ページを表示するボタン-->
                <button type="button" class="btn btn-sm btn-outline-secondary"onclick="location.href='{% url "photo:photo_detail" record.pk %}'">View</button>
                <!--カテゴリを表示するボタン-->
                <button type="button" class="btn btn-sm btn-outline-secondary"onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'" >{{record.category.title}}</button>
              </div>
              <!--投稿したユーザー名を出力-->
              <a href="{% url "photo:user_list" user=record.user.id %}">
                <small class="text-muted">{{record.user.username}}</small>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

photo/templates/photos_title.html
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Yoshimo Gallery</h1>
        <p class="lead text-muted">
          コメントを見て写真に描かれた世界に思いを馳せましょう。
          素敵な写真とコメントをお待ちしています。
        </p>
        <p>
          {% if user.is_authenticated %}
            <!--ログインしている-->
            <a href="{% url "photo:post" %}" class="btn btn-primary my-2">投稿する</a>
            <a href="{% url "accounts:logout" %}" class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
            <a href="{% url "accounts:signup" %}" class="btn btn-primary my-2">今すぐサインアップ</a>
            <a href="{% url "accounts:login" %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

  

photo/templates/post_success.html
<!--ベーステンプレートを適用-->
{% extends 'base.html' %}


{% block title %}
    Post Success
{% endblock title %}

{% block contents %}
    <br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>投稿が完了しました!</h4>
            </div>
        </div>
    </div>
{% endblock contents %}
    